### ISSUE TITLE
AM mode switch to FM mode step value not 100K

### ISSUE THREAD

**Issue by fei666888** [ralphxavier/SI4735#2]
Hi，Thanks for sharing such a cool radio. I made one based on the data. It is now my favorite radio, but I found a bug that bothers me.
Switching from AM to FM mode, the step value is no longer 100K, which will cause the FM frequency to fail to align with 100K, and reception problems

**Comment by fei666888** [comment]
When meet the bug. I can only use "PRESET" to make the  fequence align  to 100K again.

**Comment by ralphxavier** [comment]
Problem solved in version 4.1. Please update your setup.
