### ISSUE TITLE
Volume at 0 will not turn off the speaker

### ISSUE THREAD

**Issue by a1258916621** [ralphxavier/SI4735#3]
Hi ralphxavier！Thank you so much for sharing such a cool project.I met a problem.
1:When the volume is 0, the speaker still has sound output.2:The FM frequency range of the new firmware does not start from 67Mhz.The shortwave frequency will be offset by about 1K,Maybe it's a problem with my hardware。Anyway, thanks again！

**Comment by ralphxavier** [comment]
For the first issue:

	It's not a bug. It is encoded to avoid no audio.
	
	To change this behavior, follow the instructions below:
	
	Using the "Si473x_Rotary_Encoder_Interface_V4.1.ino" sketch:
	
	line 248
	
		From
			uint8_t MinVOL             = 20;
		To
			uint8_t MinVOL             = 0;
		
	
	line 1414
	
		From
			vol = map(vol, 20, 63, 0, 203 - 2);
		To
			vol = map(vol, MinVOL, MaxVOL, 0, 203 - 2);
		
For the second issue:

	Using the "Si473x_Rotary_Encoder_Interface_V4.1.ino" sketch, change:
	
	line 635
	
		From:
	 		{   "FM", FM_BAND_TYPE,  FM,  8750, 10800,  8930, 10, 0, 0}, //  FM          0
		To:
	 		{   "FM", FM_BAND_TYPE,  FM,  6700, 10800,  8930, 10, 0, 0}, //  FM          0

**Comment by ralphxavier** [comment]
It's not a bug. See instructions in the comments above.
