### ISSUE TITLE
The SI4732A10 chip has only mono mode on the FM band instead of stereo.

### ISSUE THREAD

**Issue by Piligrim-77** [ralphxavier/SI4735#6]
I assembled a receiver with a SI4732A10 chip. I connected a separate headphone amplifier to each of the pins 1 and 16 on the chip. The amplifier is tested and each channel works separately. But on the FM band I only have mono mode (I don't hear stereo in headphones), while the TTGO screen shows that stereo is working. I have tried firmware V3 and V4.1 and there is no stereo anywhere. Is this a problem in the SI4732A10 chip or in the firmware? How it can be fixed?

**Comment by Piligrim-77** [comment]
If this problem cannot be fixed, then I recommend that you add to the firmware description that the audio output only works in mono mode, even if you connect a separate amplifier to the left channel and the right channel, the stereo will not work.

**Comment by ralphxavier** [comment]
I will look into this issue next weekend.

**Comment by ralphxavier** [comment]
I did several tests with my si4735 and apparently it's working without problems. I'm buying a stereo transmitter (si4713) so I can do more testing. In the meantime, try adding the following lines at the end of the "setup()" section in the sketch and test again. These parameters will force stereo on the SI473x.

  rx.setFmBlendStereoThreshold(0);
  rx.setFmBlendMonoThreshold(0);
  rx.setFmBlendRssiStereoThreshold(0);
  rx.setFmBLendRssiMonoThreshold(0);
  rx.setFmBlendSnrStereoThreshold(0);
  rx.setFmBLendSnrMonoThreshold(0);
  rx.setFmBlendMultiPathStereoThreshold(100);
  rx.setFmBlendMultiPathMonoThreshold(100);

**Comment by Piligrim-77** [comment]
Thank you so much for your help! Yes, these lines helped turn on the stereo mode. I also added an extra line:

si4735.setFmStereoOn();
